cp /home/rbiazo/.config/fish/config.fish /home/rbiazo/GitHub/ConfigFiles/config.fish
cp /home/rbiazo/.config/rofi/config.rasi /home/rbiazo/GitHub/ConfigFiles/config.rasi
cp /home/rbiazo/.config/i3/config /home/rbiazo/GitHub/ConfigFiles/config_i3
cp /home/rbiazo/.config/kitty/kitty.conf /home/rbiazo/GitHub/ConfigFiles/kitty.conf
cp /home/rbiazo/.config/polybar/config.ini /home/rbiazo/GitHub/ConfigFiles/config.ini
cp /etc/lightdm/lightdm.conf /home/rbiazo/GitHub/ConfigFiles/lightdm.conf
cp /etc/lightdm/slick-greeter.conf /home/rbiazo/GitHub/ConfigFiles/slick-greeter.conf
cp /etc/xdg/picom.conf /home/rbiazo/GitHub/ConfigFiles/picom.conf
cp /home/rbiazo/x /home/rbiazo/GitHub/ConfigFiles/x
cp /home/rbiazo/mini /home/rbiazo/GitHub/ConfigFiles/mini
